class AgentMiddleware:
    priority = 100
    
    def __init__(self, *, name=None):
        self.name = name or self.__class__.__name__

    async def before_run(self, context): ...
    async def before_step(self, step, context): ...
    async def before_tool(self, step, tool_name, params, context): ...
    async def after_tool(self, step, tool_name, result, context): ...
    async def after_step(self, step, result, context): ...
    async def after_run(self, context, final_result): ...
